import type { NextPage } from 'next'
import Head from 'next/head'
import { ConnectKitButton } from 'connectkit'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex items-center justify-center h-screen w-full">
        <ConnectKitButton />
      </div>
    </div>
  )
}

export default Home
